package devcontainer

import (
	"reflect"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func translate(t *testing.T, file string, in Input) (Setup, composeFile) {
	t.Helper()
	f, err := Parse([]byte(file), vars)
	if err != nil {
		t.Fatal(err)
	}
	if in.Path == "" {
		in.Path = ".devcontainer/devcontainer.json"
	}
	if in.Worktree == "" {
		in.Worktree = "/wt/pr-7"
	}
	s, err := Translate(f, in)
	if err != nil {
		t.Fatal(err)
	}
	var c composeFile
	if err := yaml.Unmarshal(s.Compose, &c); err != nil {
		t.Fatalf("the generated file is not YAML: %v\n%s", err, s.Compose)
	}
	return s, c
}

func TestTranslateAnImage(t *testing.T) {
	s, c := translate(t, tryNode, Input{Start: "npm start"})
	if s.Service != Service || s.Files != nil || s.Services != nil {
		t.Errorf("setup = %+v", s)
	}
	dev := c.Services[Service]
	if dev.Image != "mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye" || dev.WorkingDir != "/workspaces/shop" {
		t.Errorf("service = %+v", dev)
	}
	// The worktree is the workspace: what a reviewer has is what runs.
	want := []volume{{Type: "bind", Source: "/wt/pr-7", Target: "/workspaces/shop"}}
	if !reflect.DeepEqual(dev.Volumes, want) {
		t.Errorf("volumes = %+v", dev.Volumes)
	}
	// It shows what the start command writes, and Compose reads no
	// variable of its own in it.
	if len(dev.Entrypoint) != 3 || !strings.Contains(dev.Entrypoint[2], "tail -f "+LogFile) || !strings.Contains(dev.Entrypoint[2], "wait $$!") {
		t.Errorf("entrypoint = %q", dev.Entrypoint)
	}
	if s.Waits {
		t.Error("a container with a start command does more than wait")
	}
	if dev.Command == nil || !strings.Contains(string(s.Compose), "command: !reset []") {
		t.Errorf("a compose file's command would follow the entrypoint:\n%s", s.Compose)
	}
	if !strings.HasPrefix(string(s.Compose), "# Generated by pit from .devcontainer/devcontainer.json") {
		t.Errorf("the file does not say where it is from:\n%s", s.Compose)
	}
	if len(s.Create) != 1 || s.Create[0].Phase != "postCreateCommand" || len(s.Update) != 0 || len(s.Started) != 0 {
		t.Errorf("create = %+v, update = %+v, started = %+v", s.Create, s.Update, s.Started)
	}
}

func TestTranslateWithoutAStartCommand(t *testing.T) {
	s, c := translate(t, tryNode, Input{})
	if e := c.Services[Service].Entrypoint; len(e) != 3 || !strings.Contains(e[2], "while sleep 1000") {
		t.Errorf("entrypoint = %q", e)
	}
	if !s.Waits {
		t.Error("a container that only waits says so")
	}

	// Its own command, when the file keeps it.
	s, c = translate(t, `{"image": "nginx", "overrideCommand": false}`, Input{})
	if e := c.Services[Service].Entrypoint; e != nil || c.Services[Service].Command != nil || s.Waits {
		t.Errorf("entrypoint = %q, waits = %v", e, s.Waits)
	}
}

func TestTranslateABuild(t *testing.T) {
	_, c := translate(t, `{
		"build": {"dockerfile": "Dockerfile", "context": "..", "args": {"V": "$HOME"}, "target": "dev"},
		"workspaceMount": "source=${localWorkspaceFolder},target=/src,type=bind,consistency=cached",
		"workspaceFolder": "/src/app",
		"mounts": ["source=cache,target=/cache,type=volume"],
		"containerUser": "app",
		"containerEnv": {"A": "1"},
		"init": true, "privileged": true, "capAdd": ["SYS_PTRACE"], "securityOpt": ["seccomp=unconfined"]
	}`, Input{})
	dev := c.Services[Service]
	want := &build{Context: "/wt/pr-7", Dockerfile: "/wt/pr-7/.devcontainer/Dockerfile", Args: map[string]string{"V": "$$HOME"}, Target: "dev"}
	if !reflect.DeepEqual(dev.Build, want) || dev.Image != "" {
		t.Errorf("build = %+v", dev.Build)
	}
	wantVolumes := []volume{
		{Type: "bind", Source: "/wt/pr-7", Target: "/src"},
		{Type: "volume", Source: "cache", Target: "/cache"},
	}
	if !reflect.DeepEqual(dev.Volumes, wantVolumes) {
		t.Errorf("volumes = %+v", dev.Volumes)
	}
	// Declared, a named volume is the sandbox's own.
	if _, ok := c.Volumes["cache"]; !ok || len(c.Volumes) != 1 {
		t.Errorf("volumes = %v", c.Volumes)
	}
	if dev.User != "app" || dev.Environment["A"] != "1" || dev.Init == nil || !*dev.Init || !dev.Privileged ||
		!reflect.DeepEqual(dev.CapAdd, []string{"SYS_PTRACE"}) || !reflect.DeepEqual(dev.SecurityOpt, []string{"seccomp=unconfined"}) {
		t.Errorf("service = %+v", dev)
	}
}

func TestTranslateRunArgs(t *testing.T) {
	s, c := translate(t, `{"image": "x", "runArgs": [
		"--cap-add=NET_ADMIN", "--security-opt", "apparmor=unconfined", "--privileged", "--init",
		"-e", "A=b$c", "--env=D=e", "-u", "1000", "--network=host", "--shm-size", "1g"]}`, Input{})
	dev := c.Services[Service]
	if !reflect.DeepEqual(dev.CapAdd, []string{"NET_ADMIN"}) || !reflect.DeepEqual(dev.SecurityOpt, []string{"apparmor=unconfined"}) ||
		!dev.Privileged || dev.Init == nil || !*dev.Init || dev.User != "1000" ||
		!reflect.DeepEqual(dev.Environment, map[string]string{"A": "b$$c", "D": "e"}) {
		t.Errorf("service = %+v", dev)
	}
	if !reflect.DeepEqual(s.Ignored, []string{"runArgs --network=host --shm-size 1g"}) {
		t.Errorf("ignored = %q", s.Ignored)
	}
}

func TestTranslateSaysWhatItLeavesOut(t *testing.T) {
	s, _ := translate(t, `{"image": "x",
		"features": {"ghcr.io/devcontainers/features/node:1": {}, "ghcr.io/devcontainers/features/git:1": {}},
		"initializeCommand": "touch .env",
		"postAttachCommand": "echo hi"}`, Input{})
	want := []string{
		"features (ghcr.io/devcontainers/features/git:1, ghcr.io/devcontainers/features/node:1): the container runs without them",
		"initializeCommand: it would run on this machine, outside the container",
		"postAttachCommand: it runs when an editor attaches, and pit does not",
	}
	if !reflect.DeepEqual(s.Ignored, want) {
		t.Errorf("ignored = %q", s.Ignored)
	}
	if s, _ := translate(t, tryNode, Input{}); s.Ignored != nil {
		t.Errorf("ignored = %q", s.Ignored)
	}
}

func TestTranslateComposeFiles(t *testing.T) {
	s, c := translate(t, `{
		"dockerComposeFile": ["../docker-compose.yml", "docker-compose.extend.yml"],
		"service": "app",
		"runServices": ["db", "app"],
		"workspaceFolder": "/workspace",
		"remoteUser": "vscode",
		"remoteEnv": {"X": "1"},
		"onCreateCommand": "a", "updateContentCommand": "b", "postCreateCommand": "c", "postStartCommand": "d"
	}`, Input{Path: ".devcontainer/devcontainer.json"})
	if !reflect.DeepEqual(s.Files, []string{"docker-compose.yml", ".devcontainer/docker-compose.extend.yml"}) {
		t.Errorf("files = %q", s.Files)
	}
	if s.Service != "app" || !reflect.DeepEqual(s.Services, []string{"app", "db"}) {
		t.Errorf("service = %q, services = %q", s.Service, s.Services)
	}
	// The compose files say how it runs; without a start command pit
	// adds nothing to it.
	app, ok := c.Services["app"]
	if !ok || !reflect.DeepEqual(app, service{}) || s.Waits {
		t.Errorf("app = %+v, waits = %v\n%s", app, s.Waits, s.Compose)
	}
	if s.Workdir != "/workspace" || s.User != "vscode" || s.Env["X"] != "1" {
		t.Errorf("setup = %+v", s)
	}
	phases := func(c Commands) (out []string) {
		for _, cmd := range c {
			out = append(out, cmd.Phase+":"+cmd.Shell)
		}
		return out
	}
	if got := phases(s.Create); !reflect.DeepEqual(got, []string{"onCreateCommand:a", "updateContentCommand:b", "postCreateCommand:c"}) {
		t.Errorf("create = %q", got)
	}
	if got := phases(s.Update); !reflect.DeepEqual(got, []string{"updateContentCommand:b"}) {
		t.Errorf("update = %q", got)
	}
	if got := phases(s.Started); !reflect.DeepEqual(got, []string{"postStartCommand:d"}) {
		t.Errorf("started = %q", got)
	}

	// With one, pit's own start replaces the service's command, and so
	// does overrideCommand.
	for _, file := range []string{
		`{"dockerComposeFile": "c.yml", "service": "app"}`,
		`{"dockerComposeFile": "c.yml", "service": "app", "overrideCommand": true}`,
	} {
		start := ""
		if !strings.Contains(file, "overrideCommand") {
			start = "rails s"
		}
		_, c := translate(t, file, Input{Start: start})
		if len(c.Services["app"].Entrypoint) != 3 {
			t.Errorf("%s: entrypoint = %q", file, c.Services["app"].Entrypoint)
		}
	}
}

func TestExecRunsAsTheFileSays(t *testing.T) {
	s := Setup{Service: "app", User: "vscode", Workdir: "/workspace", Env: map[string]string{
		"PATH": "${PATH}:/x", "Q": `say "hi" \ ` + "`now`",
	}}
	exports := `export PATH="${PATH}:/x"; export Q="say \"hi\" \\ ` + "\\`now\\`" + `"; `
	got := s.Exec(Command{Shell: "npm install"})
	want := []string{"exec", "-T", "-u", "vscode", "-w", "/workspace", "app", "/bin/sh", "-c", exports + "npm install"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got  %q\nwant %q", got, want)
	}
	got = s.Exec(Command{Args: []string{"make", "a b"}})
	want = []string{"exec", "-T", "-u", "vscode", "-w", "/workspace", "app", "/bin/sh", "-c", exports + `exec "$@"`, "sh", "make", "a b"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got  %q\nwant %q", got, want)
	}
	got = Setup{Service: "dev"}.StartExec("npm start")
	want = []string{"exec", "-T", "-d", "dev", "/bin/sh", "-c", "exec >>" + LogFile + " 2>&1; npm start"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got  %q\nwant %q", got, want)
	}
}

func TestAdoptWhatTheImageSays(t *testing.T) {
	s, _ := translate(t, tryNode, Input{})
	s.Env = map[string]string{"MINE": "1", "BOTH": "file"}
	label := `[
		{"id": "ghcr.io/devcontainers/features/node:1", "remoteEnv": {"BOTH": "image", "NODE": "yes"}, "postCreateCommand": "feature-setup"},
		{"remoteUser": "node", "postStartCommand": ["echo", "up"], "onCreateCommand": "once"}
	]`
	if err := s.Adopt(label); err != nil {
		t.Fatal(err)
	}
	if s.User != "node" {
		t.Errorf("user = %q", s.User)
	}
	if !reflect.DeepEqual(s.Env, map[string]string{"MINE": "1", "BOTH": "file", "NODE": "yes"}) {
		t.Errorf("env = %v", s.Env)
	}
	var create []string
	for _, c := range s.Create {
		create = append(create, c.String())
	}
	if !reflect.DeepEqual(create, []string{"feature-setup", "once", "npm install"}) {
		t.Errorf("create = %q", create)
	}
	if len(s.Started) != 1 || s.Started[0].String() != "echo up" {
		t.Errorf("started = %+v", s.Started)
	}

	// The file's own user wins; one entry needs no list.
	s, _ = translate(t, `{"image": "x", "remoteUser": "root"}`, Input{})
	if err := s.Adopt(`{"remoteUser": "node"}`); err != nil || s.User != "root" {
		t.Errorf("user = %q, %v", s.User, err)
	}
	s, _ = translate(t, `{"image": "x"}`, Input{})
	if err := s.Adopt(`{"containerUser": "app"}`); err != nil || s.User != "app" {
		t.Errorf("user = %q, %v", s.User, err)
	}
	if err := s.Adopt(""); err != nil {
		t.Error(err)
	}
	if err := s.Adopt("not json"); err == nil {
		t.Error("a label that is not JSON was taken")
	}
}
